# Generated by Django 2.0.7 on 2020-06-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
