# Generated by Django 3.0.6 on 2020-09-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200910_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lessonsCompleted',
        ),
    ]
