# Generated by Django 3.0.6 on 2020-10-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lessonscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='zero',
            field=models.IntegerField(default=0),
        ),
    ]
