# Generated by Django 3.0.6 on 2020-10-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_zero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='zero',
        ),
    ]
