# Generated by Django 2.0.7 on 2020-06-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Gratis', 'gra'), ('Profesional', 'pro'), ('Amateur', 'ama')], default='Free', max_length=30),
        ),
    ]
