# Generated by Django 2.0.7 on 2020-06-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20200625_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Profesional', 'pro'), ('Gratis', 'gra'), ('Amateur', 'ama')], default='Free', max_length=30),
        ),
    ]
