# Generated by Django 3.0.6 on 2020-09-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_auto_20200628_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Profesional', 'pro'), ('Amateur', 'ama'), ('Gratis', 'gra')], default='Gratis', max_length=30),
        ),
    ]
