# Generated by Django 3.0.6 on 2020-10-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0008_auto_20200911_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Gratis', 'gra'), ('Amateur', 'ama'), ('Profesional', 'pro')], default='Gratis', max_length=30),
        ),
    ]
