# Generated by Django 3.0.6 on 2020-10-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0009_auto_20201001_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Amateur', 'ama'), ('Gratis', 'gra'), ('Profesional', 'pro')], default='Gratis', max_length=30),
        ),
    ]
