# Generated by Django 3.0.6 on 2020-10-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0010_auto_20201001_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Profesional', 'pro'), ('Gratis', 'gra'), ('Amateur', 'ama')], default='Gratis', max_length=30),
        ),
    ]
